Fix exception when saving CSV
The removal of the `.astype` calls in the previous commit to `main` causes an exception when saving the CSV file:

```bash
Traceback (most recent call last):
  File "../../pycryptobot.py", line 964, in main
    executeJob(s, app, state)
  File "../../pycryptobot.py", line 925, in executeJob
    account.saveTrackerCSV()
  File "/home/sandbox/pycryptobot/models/TradingAccount.py", line 363, in saveTrackerCSV
    df_tracker['profit'] = np.subtract(np.subtract(df_tracker['sell_value'], df_tracker['buy_value']), np.add(df_tracker['buy_fees'], df_tracker['sell_fees']))
  File "/usr/lib/python3/dist-packages/pandas/core/series.py", line 812, in __array_ufunc__
    result = ops.maybe_dispatch_ufunc_to_dunder_op(
  File "/usr/lib/python3/dist-packages/pandas/core/ops/__init__.py", line 1740, in maybe_dispatch_ufunc_to_dunder_op
    return getattr(self, name, not_implemented)(inputs[1])
  File "/usr/lib/python3/dist-packages/pandas/core/ops/__init__.py", line 1048, in wrapper
    result = na_op(lvalues, rvalues)
  File "/usr/lib/python3/dist-packages/pandas/core/ops/__init__.py", line 970, in na_op
    result = masked_arith_op(x, y, op)
  File "/usr/lib/python3/dist-packages/pandas/core/ops/__init__.py", line 447, in masked_arith_op
    result[mask] = op(xrav[mask], com.values_from_object(yrav[mask]))
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```